### PR TITLE
GSoC: documentation

### PR DESCRIPTION
**Pull request by unkcpz**
- Change the doc theme same as kiwipy
- add docstring to all public methods
- add new examples
- reorganize the section of the doc.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
you can remove all the `type`/`rtype` in these docstrings, in favour of #180 😄

**Comment by chrisjsewell** [comment]
I also added sphinx-autobuild to tox 806f932a245ef19cfe001b70b80eaffc05eb3b28

**Comment by unkcpz** [comment]
> you can remove all the type/rtype in these docstrings

@chrisjsewell thanks! will do it.

also a good reminder, here is an unfinished PR. :smile:

**Comment by chrisjsewell** [comment]
Haha yeh happy to help you finish this. 
It's on my todo list to add documentation about the engine to aiida-core, so would save me work if I can just link to these docs 😝

**Comment by chrisjsewell** [comment]
Hey @unkcpz lets get this done and dusted 😀 
Few conflicts to fix from #180, and just let me know if you need any help or when its ready for review cheers

**Review by chrisjsewell — CHANGES_REQUESTED** [review]

**Comment by unkcpz** [comment]
@chrisjsewell thanks! I plan to come back to make this done after #180 merged.
Well... since you copy this, what is the correct way to continue this PR?

**Comment by chrisjsewell** [comment]
> Well... since you copy this, what is the correct way to continue this PR?

Well as I was reviewing, I realised there was a lot to change/add lol. So yeh I would say, once I have finished it (hopefully today), to check that you are happy I have included everything from this PR in #190, then close it

**Comment by chrisjsewell** [comment]
I will close this for now, since it has been essentially superseded by #190 and #192

**Pull request closed without merging**
