### PR TITLE
Defer import of aio_pika

### PR DESCRIPTION
**Pull request by unkcpz**
Replace #287 

(I'll do a benchmark on import aiida.orm with this)

### CODE REVIEW

**Comment by unkcpz** [comment]
I didn't detect any import performance improvement, maybe I did something wrong? @danielhollas 

I run:

```bash
hyperfine -w 5 'python -c "import aiida.orm"'
```

**Comment by sphuber** [comment]
> I didn't detect any import performance improvement, maybe I did something wrong? @danielhollas
> 
> I run:
> 
> ```shell
> hyperfine -w 5 'python -c "import aiida.orm"'
> ```

Well, you now add the imports to `plumpy.exceptions` and that is star-imported in `plumpy/__init__.py` so you are undoing moving the import in `plumpy.processes` are you not?

**Comment by unkcpz** [comment]
> plumpy.exceptions and that is star-imported in plumpy/__init__.py 

Right, that's true. But it is not easy to seperate the aiopika exception from the regular exceptions. I create and `rmq` module for that but it seems a bit overkill. 
I am working on adding support for not using rabbitmq, and in the end I think it should have plumpy to support both. A good start would to have a module for things that related to rabbitmq related libraries (aio_pika, kiwipy..).

**Comment by unkcpz** [comment]
I'll include this in #297, since this is not urgent fix.

**Pull request closed without merging**
