### PR TITLE
Type extension aiopika workaround

### PR DESCRIPTION
**Pull request by unkcpz**
Based on #289

### CODE REVIEW

**Comment by sphuber** [comment]
What is the scope of this PR @unkcpz You referenced it in #289 saying that this should just fix the `typing_extensions` import error. But there seem to be a lot of changes here.

**Comment by unkcpz** [comment]
After #289 there is only the last commit will fix `typing_extensions` error. That one should go first.

**Comment by sphuber** [comment]
> After #289 there is only the last commit will fix `typing_extensions` error. That one should go first.

I don't understand. Do you mean in this PR you just mean to merge [ef7b10b](https://github.com/aiidateam/plumpy/pull/292/commits/ef7b10b3b4226056b59be4c4b9da8e8d7b399fc5) ? If so, could you please update the branch to just include that commit?

**Comment by unkcpz** [comment]
> Do you mean in this PR you just mean to merge [ef7b10b](https://github.com/aiidateam/plumpy/pull/292/commits/ef7b10b3b4226056b59be4c4b9da8e8d7b399fc5) ?

Yes.

> If so, could you please update the branch to just include that commit?

But the PR was from the branch of my fork. 
Sorry if it is confusing.

**Comment by sphuber** [comment]
Yeah, but now this PR would change over a 1000 lines. Surely that is not the intention?

**Comment by unkcpz** [comment]
Yes, I was waiting for the merge of #289 :) I should put "blocked" tag for this one.

**Comment by sphuber** [comment]
But there the CI is failing because of the fix you put here? Why not just put just that fix in this PR, we merge that, and then you update the other PR and tests will pass. Since the fix doesn't touch any of the other changes, there should be no conflicts whatsoever. In fact, you would just do on the branch of this PR
```
git reset --hard origin/master
git cherry-pick ef7b10b3b4226056b59be4c4b9da8e8d7b399fc5
```
Now you just have the commit with the fix

**Comment by unkcpz** [comment]
I see. Not sure what I did I tried with cherry-pick but it closes the PR. I'll open a new one with the change.

**Pull request closed without merging**
