### PR TITLE
bump nest-asyncio version

### PR DESCRIPTION
**Pull request by ltalirz**
jupyter-client 7 requires nest-asyncio>=1.5

### CODE REVIEW

**Comment by ltalirz** [comment]
This was causing pip conflicts in https://github.com/aiidalab/aiidalab-widgets-base/issues/228#issuecomment-919028517

**Comment by ltalirz** [comment]
@sphuber Do you think the test failures like

```
>           if msg['parent_header'].get('msg_id') == msg_id:
E           TypeError: 'coroutine' object is not subscriptable
``` 
are related to this update?

It's not urgent; just something that would be good to update once we get around to it

**Comment by csadorf** [comment]
@ltalirz I am going to pick up this effort.

**Comment by sphuber** [comment]
Superseded by #229

**Pull request closed without merging**
