### PR TITLE
🐛 FIX: Cleanup process event hooks

### LINKED ISSUE #197: Release event hooks when process is terminated
The three referencing lambda functions I identified in https://github.com/aiidateam/aiida-core/issues/4603#issuecomment-767646196 are from `plumpy.Process._setup_event_hooks` (https://github.com/aiidateam/plumpy/blob/848028bb6b066b904bd7941f9560ececa97136d2/plumpy/processes.py#L318-L330).
So I imagine these event hooks need to be removed, once the process enters a terminal state.

_Originally posted by @chrisjsewell in https://github.com/aiidateam/aiida-core/issues/4603#issuecomment-768890925_

### PR DESCRIPTION
**Pull request by chrisjsewell**
fixes #197

### CODE REVIEW

**Comment by chrisjsewell** [comment]
something like this @muhrin?

**Comment by muhrin** [comment]
Yes, this looks good.  I also think that the class should just explicitly clear all event hooks callbacks when it terminates.  The specification is quite clear about there being no more transitions after termination.  If you do this it would be good to make sure it just ignore anyone 'unhooking' themselves and not being found in this case.

**Comment by chrisjsewell** [comment]
ok cheers, I'll have a think; the current solution is not quite working at the moment anyway, because cleanups are "initialised" in the "init" method, but hooks are initialised earlier in the `__init__`

**Comment by chrisjsewell** [comment]
perhaps this then: e0596e5? or is there a better place to put it?

**Comment by chrisjsewell** [comment]
>  If you do this it would be good to make sure it just ignore anyone 'unhooking' themselves and not being found in this case.

not quite sure what you mean by this 😬 do you think this needs additional logic?

**Comment by ltalirz** [comment]
> not quite sure what you mean by this 😬 do you think this needs additional logic?

I guess he meant that if you kept your original implementation where you registered the cleanup functions, one would need to make sure those don't error when you explicitly clear the event callbacks.
But it looks to me like your modified approach removes the need for this.

Just to check: this change does remove the references to the process in your test case, right?

**Comment by muhrin** [comment]
Ah, I just meant that if the class automatically clear all clients that have registered themselves for transition hooks it should not cause an error if a client then asks to unregister themselves after termination (which I presume it would it the callback method isn't found in the dictionary of registered clients).

**Comment by muhrin** [comment]
So, if I'm reading this current implementation this doesn't achieve what I'm getting at because for the moment you've just removed the call that would unregister the client.  This is totally fine (as a client can now assume it is unregistered automatically on termination), however it should also be fine for a client to have 'dumb' code that unconditionally unregisters and this should always work (whether the process has terminated or not).

**Comment by chrisjsewell** [comment]
> Just to check: this change does remove the references to the process in your test case, right?

Yes, applying this and also setting `self.state_machine = None` in `Finished.__init__`:

```python
root@0d026cab8612:~# verdi shell
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import gc 
   ...: from aiida_sleep.cli import run_calc 
   ...: from aiida_sleep.sleep_job import SleepCalculation 
   ...: from pympler import muppy, refbrowser 
   ...:  
   ...: run_calc(payload=int(1e5), output=int(1e5))                                                                                   
Out[1]: <CalcJobNode: uuid: 0fc71c1f-b870-4fa4-b1e9-51e49443a377 (pk: 81) (aiida.calculations:sleep)>

In [2]: gc.collect() 
   ...: all_objects = muppy.get_objects() 
   ...: calcs = [o for o in all_objects if hasattr(o, "__class__") and isinstance(o, SleepCalculation)] 
   ...: len(calcs)                                                                                                                    
Out[2]: 1

In [3]: cb = refbrowser.ConsoleBrowser(calcs[0], maxdepth=3) 
   ...: tree = cb.get_tree() 
   ...: cb.print_tree(tree)                                                                                                           
aiida_sleep.sleep_job.SleepCalculation-+-list--dict-+-list
                                       |            +-dict
                                       |            +-dict
                                       |            +-dict
                                       |            +-dict
                                       |            +-dict
                                       |            +-IPython.core.interactiveshell.DummyMod
                                       |            +-dict
                                       |            +-dict
                                       |
                                       +-list--dict-+-list
                                       |            +-dict
                                       |            +-dict
                                       |            +-dict
                                       |            +-dict
                                       |            +-dict
                                       |            +-IPython.core.interactiveshell.DummyMod
                                       |            +-dict
                                       |            +-dict
                                       |
                                       +-list-+-list--dict
                                              +-hamt_bitmap_node-+-list
                                                                 +-hamt
```

so still not releasing, but the tree is getting smaller!

**Comment by chrisjsewell** [comment]
>  however it should also be fine for a client to have 'dumb' code that unconditionally unregisters and this should always work (whether the process has terminated or not).

so do you mean that in:

```python
    def remove_state_event_callback(self, hook: Hashable, callback: EVENT_CALLBACK_TYPE) -> None:
        try:
            self._event_callbacks[hook].remove(callback)
        except (KeyError, ValueError):
            raise ValueError("Callback not set for hook '{}'".format(hook))
```

we should ignore a key error?

**Comment by ltalirz** [comment]
> 
> so still not releasing, but the tree is getting smaller!

If I understand correctly, then the first two references in the tree are the two lists you created in the ipython session (`calcs` and `tree`) as they are referenced by the ipython `DummyMod`.

That would leave only one list to be eliminated...

**Comment by chrisjsewell** [comment]
> That would leave only one list to be eliminated...

It turns out this seems to be the big issue: https://github.com/aiidateam/aiida-core/issues/4603#issuecomment-769039928

**Comment by muhrin** [comment]
> > however it should also be fine for a client to have 'dumb' code that unconditionally unregisters and this should always work (whether the process has terminated or not).
> 
> so do you mean that in:
> 
> ```python
>     def remove_state_event_callback(self, hook: Hashable, callback: EVENT_CALLBACK_TYPE) -> None:
>         try:
>             self._event_callbacks[hook].remove(callback)
>         except (KeyError, ValueError):
>             raise ValueError("Callback not set for hook '{}'".format(hook))
> ```
> 
> we should ignore a key error?

Yes, but _only_ if it's in the terminal state.

**Comment by chrisjsewell** [comment]
> Yes, but only if it's in the terminal state.

@muhrin see 4d5f1a5?

As a general update: #197 and #198 are not strictly necessary to fix the memory link, since python will clean up these cyclic references (once no other references remain). However, they do block automated garbage collection by cpython, and so without them (and perhaps anyway) we may need to think of some place to directly call garbage collection after a process has finished or something similar

(see https://github.com/aiidateam/aiida-core/pull/4699#issuecomment-770967191 and https://github.com/aiidateam/aiida-core/pull/4699#issuecomment-770999039)

**Review by muhrin — APPROVED** [review]
All good, if everyone is happy with this one please merge away.

**Pull request merged**
