### PR TITLE
🔧 MAINTAIN: Improve pre-commit and deployment

### PR DESCRIPTION
**Pull request by chrisjsewell**

### CODE REVIEW

**Comment by muhrin** [comment]
I don't really understand what's changing here if I'm honest (I'm not so hot on the CI scripts).
Could you elaborate a little?

**Comment by chrisjsewell** [comment]
Yeh so the main addition is `cd.yml`, which runs when you create a release tag (e.g. `v0.18.2`) and, if the tests pass, will automatically create and upload the release to PyPi.

Also for the pre-commit, I've made it so you don't have to run it in an environment with plumpy already installed, which means you can use the `pre-commit install` functionality (to block commits that fail the tests). Then replaced the bespoke pre-commit action with a standardised action.

**Comment by chrisjsewell** [comment]
I use the pypi deployment action for all my packages, like: https://github.com/executablebooks/markdown-it-py/actions/runs/456350841

**Comment by muhrin** [comment]
Looks great, I have much to learn :)

**Pull request merged**
