### PR TITLE
🚀 RELEASE: v0.20.0

### PR DESCRIPTION
**Pull request by sphuber**

### CODE REVIEW

**Comment by sphuber** [comment]
I tried copying your silly rocket emoticon in the commit message but without success. It just copies it as `rocket` in plain text.

**Comment by chrisjsewell** [comment]
> I tried copying your silly rocket emoticon in the commit message but without success. It just copies it as rocket in plain text

well get a better computer 😜 

why is this showing the changes from #221 as well?

**Comment by sphuber** [comment]
> > I tried copying your silly rocket emoticon in the commit message but without success. It just copies it as rocket in plain text
> 
> well get a better computer stuck_out_tongue_winking_eye
> 
> why is this showing the changes from #221 as well?

Because this is a release branch and so were merging this into `master`. That is where we tag. Than we just forward merge the release commit into `develop`.

**Comment by sphuber** [comment]
> > 
> 
> well get a better computer stuck_out_tongue_winking_eye

Just using `vim` on Ubuntu. Shouldn't be a problem. How am I supposed to get the emoticon in there?

**Comment by chrisjsewell** [comment]
Oh yeh I forgot about that merry-go-round 😬

> Just using vim on Ubuntu. Shouldn't be a problem. How am I supposed to get the emoticon in there?

I thought `vim` users always claim they can do everything, stop resisting and join the VS Code club

**Review by chrisjsewell — APPROVED** [review]

**Comment by sphuber** [comment]
Only use `vim` for commit messages because I use `git` from the CLI.

**Pull request merged**
