### PR TITLE
Add 'help' kwarg to OutputPort

### PR DESCRIPTION
**Pull request by greschd**
This allows creating nicer documentation for the outputs of AiiDA WorkChains.

### CODE REVIEW

**Comment by sphuber** [comment]
Plum has diverged enormously and this fork is basically not maintained. We are currently working on merging all the changes to the workflow engine into `aiida_core:develop`. Martin and me will be focusing on this during the coding week. It would be good if you can join us at some point and we can merge all your contributions to the codebase. You also made quite some PR's to my `aiida_core` fork in relation to the spec exposing etc.

**Comment by greschd** [comment]
Absolutely, I think that merging everything upstream will be one of my main tasks in the coding week. For most changes it should be just a matter of cherry-picking on top of the currently develop HEAD.

**Comment by greschd** [comment]
Essentially I created these PR's so I wouldn't forget about it and let it rot in one of my branches :slightly_smiling_face:

**Comment by greschd** [comment]
Closing in favor of a PR on muhrin/plumpy

**Pull request closed without merging**
