### PR TITLE
👌 IMPROVE: remove RUNNING from allowed states of `resume`

### PR DESCRIPTION
**Pull request by chrisjsewell**
This was part of #167, but I think it deserves its own commit.

Anyone see any unforeseen issues with this?

### CODE REVIEW

**Comment by muhrin** [comment]
I don't know if the case actually comes up but I had it this way because, for example, if you create awaitable at the end of a workchain step and the thing you are awaiting is already done then you can continue to 'run' skipping the waiting state, however you _do_ want to have a state transition so the persister make a checkpoint.

**Comment by chrisjsewell** [comment]
wel it was @unkcpz's addition, so I'll let him confirm if he thinks the change is really necessary

**Comment by unkcpz** [comment]
I didn't quite understand the situation @muhrin describe, could you describe it more detail? 

I remove from Ruuning state the `resume` just because I find there is not `resume` method implemented for `Running` state.

**Review by muhrin — APPROVED** [review]
My bad.  Yes, this PR should go ahead.  I was getting confused between `resume` (which cannot be triggered from a `Running` state) and `continue` (which can).

**Pull request merged**
